### ISSUE TITLE
Saving large numbers of tiddlers is bottlenecked on the server

### ISSUE THREAD

**Issue by joshuafontany** [OokTech/TW5-Bob#121]
I have been playing with importing individual tiddlers from large CSV files. My current test-batch is 1,800 rows. The browser handles this no-problem (slight delay when transfering to the $:/Import tiddler, slight delay when saving as regular tiddlers) - but Bob wants to report each tiddler name saved to the console, and I had to wait a significant time (almost 10 minutes) to confirms the saves on disk.

Best,
Josh F

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I have noticed this as well, I am not sure yet if it is Bob or if it is because the core has some delay built into saving which makes some saves take much longer than they did when I wasn't using the core for saving. I am looking into it but I don't have any solution for the moment.

**Comment by inmysocks** [comment]
After talking to Jeremy this is because by default there is a 1 second delay added by the syncer between tasks, so saving tiddlers takes at a minimum 1 second per tiddler when using the built-in syncer. I made a pull request to make this configurable so when that gets merged you will be able to set the syncer delay to 0 and Bob will save the way it did before.

**Comment by inmysocks** [comment]
there is an update on this.

Lowering the interval between save tasks being run fixes part of the problem, but it can break syncing when editing tiddlers like $:/SiteTitle from the control panel, the wiki tries to save on every keypress because the editing timeout is only active while in edit mode.
Previously Bob did some complex queue handling to remove redundant messages and make sure that this sort of thing didn't happen.
I am working on this now but I don't have a good solution yet.

**Comment by inmysocks** [comment]
It looks like fixing this is going to be more interesting than I had hoped.
The queue handling in Bob and the queue handling native to the core are not playing together as well as I thought. The core will wait one second after its queue is empty to try any more syncing tasks but in order for Bobs error handling to work it can only add tasks to the core queue one at a time.

One problem is how Bobs queue removes redundant messages, I think the core has a similar thing but I am not certain if they are exactly equivalent, and once a task is added to the core queue I don't see any way to remove it.
Bob will retry a save if it doesn't hear an ack response, but once it does hear a response for a save task it removes any retries for that task from the queue to reduce network traffic, this may not be possible when using the core task queue.

The big problem, that syncing a lot of tiddlers takes a very long time, is fixable, but we may lose some robustness in the error handling and see a bit of an increase in network traffic. Hopefully nothing too big in either case.

**Comment by joshuafontany** [comment]
Note to come back and Test this once I merge all the updates into my fork. :)

**Comment by inmysocks** [comment]
I looked into this some more and spoke to Jeremy, it looks like this isn't going to be fixed until we update the core syncer to allow it or we stop using the core syncer.

I think that updating the core with some of the queue logic I had before I was using the core syncer is the best way to go, Jeremy seemed open to the idea.

Unfortunately that means that it may be a while until this gets a real fix.

**Comment by inmysocks** [comment]
I had time to dig into this a bit and while it isn't completely fixed I managed to improve the situation significantly and I have a good idea of how to move forward with a real fix.

It turns out that after the updates to how the core handles syncing changes Bob doesn't need to do as much. The current problem (at least with version 5.2.3, I don't know when the updates happened) was that Bob had some throttling for saves that waited 200ms after the most recent change to a tiddler before sending updates to the server. When Bob was not using the core it had error handling that allowed it to send as many messages to the server as it wanted and then handle any errors afterward so the 200ms delay overlapped for all of the tasks, but the core forces tasks to be done sequentially so instead of being one 200ms delay before everything was finished it became 200ms between each save task.
Removing the 200ms delay took care of that problem, and the improvements to throttling in the core mean it isn't necessary.

There is still the problem of the saves are done sequentially, which slows it down considerably, but changing that requires some significant changes to the chooseNextTask function in syncer.js to allow it to handle failed tasks.

A better solution may be to create a SaveTiddlersTask that, if a syncadaptor allows it, can save multiple tiddlers at once and would be designed to handle the potential errors from a bulk save operation.
