### ISSUE TITLE
How does Bob load datafolders?

### ISSUE THREAD

**Issue by Arlen22** [OokTech/TW5-Bob#122]
Hello Jed,

I hope you are not offended that I do not use your plugin. So while this is probably something that I could figure out simply by exploring it, I thought perhaps it would be better to just ask you directly. 

How do you load data folders in Bob? I have heard rumors that Bob loads data folders differently than TiddlyServer does, but I'm very curious to know how it does that, since I saw that you have two commands that can be used to start the server (three if you count `--listen` but I don't know if you support that one or not). So I'm curious what the exact mechanism is that you use to handle requests for data folders, specifically whether you start an instance for each data folder and how you do that. 

I'm not planning to change how TiddlyServer is designed, because I made it to fill a specific need (running multiple Node TiddlyWiki instances at once), and memory consumption is the only drawback I have run into on a technical level. But I am exploring other areas in the server space and it seems you have already explored some of these areas, so I'm really curious what you've done. 

I've heard that Bob doesn't actually load the NodeJS server code, but rather calls bits and pieces of it as necessary to save and load tiddlers. Is that correct, and if so, what has your experience been with that. If it is not necessary to parse wikitext on the server, then we can write TiddlyWiki compatible servers in PHP or any other language we want to and even load folder wikis directly in the browser. So that's my line of thought.

**Comment by inmysocks** [comment]
Bob loads data folders using the built-in mechanism that the normal node server uses. It has a server that is almost the same as the normal server but has bits to support web sockets and the BobSaver tacked on. There is a little bit more that lets you set plugin paths and the like without setting environment variables, but they are all straightforward additions.

Bob uses the normal node backend for tiddlywiki, it just doesn't start redundant processes because tiddlyserver kept crashing my little raspberry pi home server and you said you didn't want help making tiddlyserver take less memory or be easier to configure.

So:

Bob uses the full nodejs tiddlywiki code base with the exception of the listen command itself, which is slightly modified to handle web sockets.
There is a bit of glue to allow loading from more than one data folder to avoid the complexity that comes with running different node processes for each wiki and to allow inter-wiki communication.

what you are talking about sounds much more like NoteSelf, I have been considering creating a simpler server in Julia that drops the tiddlywiki backend on the server and has the browser take care of all the rendering. Given what I already have with Bob it should be a pretty trivial setup , it is just a quick database back-end that serves an empty wiki and then whatever tiddlers go along with the wiki, probably determined by path although filters or authentication would be pretty simple to use also.

**Comment by Arlen22** [comment]
> Bob uses the normal node backend for tiddlywiki, it just doesn't start redundant processes because tiddlyserver kept crashing my little raspberry pi home server and you said you didn't want help making tiddlyserver take less memory or be easier to configure. 

I remember that specifically and I always wondered if there was a way to fix it, but until recently I had no way to do that. I'm hoping sometime I'll come up with a GUI for adjusting the settings, but as far as memory usage, I'm pretty sure it's just because of the way I load the entire tiddlywiki environment for each data folder, to keep them isolated and fully functional for development and compatibility. Unfortunately, that's a design constraint of TiddlyServer.

TiddlyServer only ever uses a single Node process, and all wikis are loaded inside that one process. Do you call `$tw.boot.boot()` for each data folder or do you have some other process that loads the data folder into Bob without actually creating the full server environment?

**Comment by inmysocks** [comment]
It uses the normal $tw.loadTiddlersFromPath or whatever it is called to load the data folders. There is no reason to call boot for every one unless you wanted to use different tiddlywiki versions on the server side of them. I have not found anything that uses the back-end to do more than hold and filter tiddlers, so calling the full boot process for each one seems excessive.
path that it gets into how the wiki objects themselves are handled and I don't think that I could explain that any better than just looking at the code.
