### ISSUE TITLE
Just some Questions

### ISSUE THREAD

**Issue by joshuafontany** [OokTech/TW5-Bob#143]
Hi Jed,

I'm trying to wrap up a beta-package for my new oembed plugin. Got a few questions about how to interface with Bob.

https://github.com/joshuafontany/TW5-oembed

1) How would I check to see if Bob in the browser has an active open websocket? Right now I'm testing for `if($tw.Bob)` to queue up a message, but I would like to test for an open connection as well, and offer people a way to manually input the oembed JSON data if Bob is not available with an open connection.

2) I seem to be getting multiple messages received by the server for each one I send from the browser. I have setup some debugging to catch and report this, and I always see the "this URL is already being processed" message pop up, which means my message handler functions are being triggered multiple times.

3) I'm not sure I am saving the new data-tiddlers to the server the correct way in my message handler. I see multiple "tiddler saved" messages.

4) Could this point to the race conditions bugs in the save-queue that is preventing saving Drafts/etc?

Best,
Joshua F

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [ ] The answer to my question isn't listed in the documentation or this isn't
  a question
- [ ] This is not a duplicate issue
- [ ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
1 - you can directly access the web socket state in the browser with $tw.connections[0].socket
the best check for if it exists and is active is probably 
if($tw.connections[0] && $tw.connections[0].socket && $tw.connections[0].socket.readyState === 1) {
// code stuff
}

2 - On the node side are you using $tw.Bob.SendToBrowser ? Using just $tw.Bob.Shared.SendMessage doesn't do some checks that can prevent multiple messages sent to the same browser.
On both sides is the first thing the handler does $tw.Bob.Shared.sendAck(data);? if not the ack message may take longer than the retry timeout depending on your settings. if you don't have it sending an ack at all it will keep trying to resend.
There may be other things to check, but those are the easy ones I can think of now.

3 - The safest option for saving is $tw.syncadaptor.saveTiddler(data.tiddler, prefix, data.source_connection); There are a bunch of places where I need to ensure that I don't have redundant functions but that should be the best option.

4 - drafts aren't saved on the server mainly to prevent spamming the server with messages and because until one of the more recent versions one persons drafts would overwrite everyone else's. The saving delay for editing draft tiddlers should handle the trouble with draft tiddlers without problems.
The bugs with directly editing a tiddler outside of draft mode seem to be handled with the fix in #142 now the only problem is that the internal syncer is still much slower than I want it to be.

**Comment by joshuafontany** [comment]
Mahalo (thanks), just what I needed to keep testing.

**Comment by joshuafontany** [comment]
2- I am only sending a message from the browser to the server. The messageHandler immediately sends the (ack) message. I am then using the saveTiddler to refresh my widget and load the embed data once it appears. The widget's native refresh handling does this well, so no need to send a separate "done" message with the data. The saveTiddler method pushes the new data tiddler to all connected browsers.

**Comment by joshuafontany** [comment]
Satisfied with this one. Closing.
