### ISSUE TITLE
System tiddlers not saving correctly,  including StoryList and ServerIP

### ISSUE THREAD

**Issue by Ca1vino** [OokTech/TW5-Bob#177]
Changes to some system tiddlers are not being saved. This makes it hard to configure and use the wiki.

Here are two examples.

If I edit $:/ServerIP and then reload the browser page, it goes back to previous edit.

$:/StoryList is not being saved either. So if DefaultTiddlers is set (via Control Panel) to reload the currently open tiddlers, this feature does not work. So it reloads DefaultTiddlers but the StoryList does not reflect what I had been doing before the reload.

Maybe related:  The Save Changes button in the sidebar does not show any activity or appear to do anything. On my other TW server it turns red then back to clear when the updates are sent.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
$:/ServerIP is information and is defined set by the current IP address of the server, it isn't saved because it can't change the server IP. There are a few system tiddlers that Bob creates, like the list of available plugins, that aren't saved because they are information about the server and editing them doesn't do anything.

By default the story list isn't saved because Bob can be used by multiple people or in multiple browsers/tabs at the same time, if story list were saved it would mean everyone using the wiki would have the same view, and whenever someone opened a tiddler it would open it for everyone. I am hoping to change this behavior in the future but I don't think it will be soon.
