### ISSUE TITLE
$:/Bob/AvailableLanguageList is not json but declared as such

### ISSUE THREAD

**Issue by psiloi** [OokTech/TW5-Bob#184]
I am under linux with node v12.22.5 and I installed bob manually as decsribed with two git clone command and the likes.

I added 4 symlinks to get around the theme/Themes problem. So Bob works OK but for localisation support.

After lauching the server, my http web client display an error message:

$:/Bob/AvailableLanguageList is set as type "application/json" and its content is "ar-PS ca-ES cs-CZ da-DK de-AT de-CH de-DE el-GR en-US es-ES fa-IR fr-FR he-IL hi-IN ia-IA it-IT ja-JP ko-KR nl-NL pa-IN pt-BR pt-PT ru-RU sk-SK sl-SI sv-SE zh-CN zh-HK zh-Hans zh-Hant zh-TW" which is not json at all.

as reported by online json validator https://jsonformatter.org/ we get:

Parse error on line 1:
ar-PS ca-ES cs-CZ da
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [X] Linux
- [ ] Other

and using

- [X] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [X] I am using the newest version
- [X] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue
- [X] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I updated Bob so that this is no longer an issue, and it also handles languages correctly.
You have to add them the same way as you add plugins in the $:/ControlPanel -> Bob -> Manage Languages, after you select which languages you want included in the wiki you have to click the Save Language Selection button then reload the page by clicking on the Refresh Page link, after that the languages you selected are under the Plugins tab in the control panel like normal.
