### ISSUE TITLE
TiddlyWiki 5.1.16 has a hook on server startup

### ISSUE THREAD

**Issue by Arlen22** [OokTech/TW5-Bob#29]
I was looking through your code, and I noticed that you start a separate server for the websockets. A pull request was merged recently which adds a hook to the server command that passes both the SimpleServer instance and the Node HTTP server instance, allowing you to attach handlers to them without modifying core code. You just need to make sure you attach the hook before the startup task is called that starts the server command (I forget which one it is). You can use it to attach the websockets listener to the server. You can also use it to add route handlers to the SimpleServer instance so you can serve other requests for the data folder (uploads stored in the data folder, for example). 

The pull request was merged in time for 5.1.16. Just thought you might like to know that as it seems it would be quite useful to you in several ways. 

The PR is here: https://github.com/Jermolene/TiddlyWiki5/pull/3024

**Comment by Arlen22** [comment]
I just thought I'd mention a few things in connection with TiddlyServer.

* I like your work. I think some of these features should be in core (like the file watcher and multiuser editing), but I don't know what the best way to do that is yet.
* TiddlyServer basically uses all the code from the server command. It uses the server command's request handler, which means that any routes a plugin adds will also be called. I'm adding the hook code to TiddlyServer as I write this, although the node server argument will be an EventEmitter, and there is an additional argument with the string `tiddlyserver`. 
* Some parts of your plugin will probably work with TiddlyServer and some probably won't. However, I would be very interested in helping to support features that don't currently work. 
* I want to find a way to work with Websockets if there are plugins that require websocket support like yours does. I have thought of a couple ways, but I'm not sure which is the best. What are your thoughts? I can't just pass in the node server to every plugin that wants to add websockets. But if the plugin wants to support TiddlyServer it could, since TiddlyServer makes its presence known. We could also add websocket support to the core or as a separate tiddlywiki plugin. Actually as a plugin would work perfect. What are your thoughts? It would mean users would need to specify both for your plugin to work correctly, but is that that big of a deal? The server command displays an error message if the required plugins are not specified. 

I like your work and I can see that you understand how TiddlyWiki works under the hood. It is interesting to see how you take advantage of the global $tw object.

**Comment by inmysocks** [comment]
I don't see what the benefit of having tiddlyserver and Bob together at the same time would be.

The http server that is currently in the core would not work for Bob. The wsserver command is misnamed now and the only reason I haven't changed it is backwards compatibility. It doesn't use websockets, it is the core server extended to provide a static file server and be able to server multiple wikis and to be able to dynamically add or remove wiki paths without restarting. I could probably take the core server object returned by the hook and add all those onto it but that would probably be even more complex than what I made.

The web socket and http server components are almost completely independent. Using the same server for both of them would make it much more complex and much harder to maintain or extend. As it is the web socket server created is a generic and extensible server that has just enough on it to bootstrap the tiddlywiki connections. Everything else is added on afterward. I don't know what web socketsupport you want to add on top of that, it can already be used for other plugins.

I have been looking at how to add components of Bob into the core but a lot of it is built on the assumption of multiple wikis being served and there would have to be some sort of consensus about it. And if it did get moved into the core there are changes to boot.js and the architecture of tiddlywiki that would make more sense to have support for multiple wikis built into tiddlywiki at a lower level.
I haven't found a backwards compatible way to merge any of Bob into the core because of this.

**Comment by Arlen22** [comment]
- TiddlyServer serves multiple wikis and other files also, but I don't understand the difference between it and Bob yet. Maybe they both aim to accomplish the same thing. 
 - I have a PR in TiddlyWiki which is the first step to allow syncadaptors to notify TW immediately of changes on the server. https://github.com/Jermolene/TiddlyWiki5/pull/3227
 - The multi-user editing feature is a real need, but it would definitely require either websockets or server-sent events, both of which I'm looking into for the core or as a core plugin.  Jeremy recommended server-sent events, and they do seem very simple, so I'm trying to see if I can get it made.
 - The file system watcher is a feature that has been requested by many for a long time. It is easily doable, I just have to figure out how to do it in the filesystem adapter. 

Beyond that, I don't know what other cases Bob covers but it seems like the rest are things that would normally stay as a plugin anyway. Your work is interesting and I'm still trying to figure out everything it covers. I am starting to see what you mean, though, about users not needing both.

**Comment by inmysocks** [comment]
One of the big differences between TiddlyServer and Bob is that Bob is a purely tiddlywiki plugin instead of a separate application.
Also Bob has a single node process for all the wikis to make inter-wiki communication and sharing tiddlers easy and to let it be incorporated into other node applications as a module.
That is, of course, in addition to allowing multiple people to use the wikis. But the reason I use it is because it keeps any browser tabs you have the wiki open in sync, not to have multiple people on the same wiki.

At the moment Bob doesn't have the same handling for single file wikis as TiddlyServer, but soon it will be able to take a single file wiki and treat it as a node wiki for editing and export back to a single file wiki when editing is finished.

The multi-user editing ability is the result of all of the other pieces together, you can't really have that on its own.

The file system monitoring component and file system adapter should probably remain separate, they have separate functions. The file system adaptor takes changes from the browser and pushes them to the file system, the monitor goes the other way. To maintain modularity and maintainability keeping them separate is a good idea.

**Comment by icarito** [comment]
Hey,
Nice work on this Plugin! I agree with @Arlen22 that some of the functionality should be in core.
I look forward to helping with the effort.

I develop a Python backend and I'd like to support the websocket protocol to be able to have collaborative sessions.

Thanks @inmysocks for developing this and for hosting this conversation.

**Comment by icarito** [comment]
@Arlen22 if we break up what parts we're interested maybe we can work together? If the feature is in core, Bob can use it and Jed doesn't need to maintain it so it's a win-win ;-)

- [x] Node-server supporting websockets (done by @Arlen22)
- [ ] Node-server watching tiddlers directory
- [ ] Node-server notifying clients thu websockets of updated files
- [ ] Client Tiddlywikis fetching changed tiddler file upon update event    <--- I'm interested in this one while the others settle.

I don't think we should implement these atm:

- [ ] File locking
- [ ] Multi-Wiki management from Control Panel

Looking forward to your comments and collaboration!
